---
title: "StatisticsOnData"
output: html_document
---

```{r}
library(dplyr)
```


# Mesure de l'effet du bruit

```{r}
curr_dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(curr_dir); setwd('./../../')

data <- read.csv("./../Setup 1/Data/simulated_1M_data.csv")

set.seed(123)

data = data[sample(nrow(data)),]
size_sample = 10000
data = data[1:size_sample,]

# Importer les hyperparamètres
hyperparams <- read.csv("./../Setup 1/Data/hyperparams.csv")
```


```{r}
# Extraire les variables nécessaires
myZ <- data$treatment
# myY <- data$Y
myX <- data %>% select(-treatment, -Y) %>% as.matrix()

# Calculer mu_0, tau, et ITE
mu_0 <- hyperparams$gamma_0 + hyperparams$gamma_1 * myX[, "age"] + hyperparams$gamma_2 * myX[, "weight"] + hyperparams$gamma_3 * myX[, "comorbidities"] + hyperparams$gamma_4 * myX[, "gender"]
tau <- hyperparams$delta_0 + hyperparams$delta_1 * myX[, "age"] + hyperparams$delta_2 * myX[, "weight"] + hyperparams$delta_3 * myX[, "comorbidities"] + hyperparams$delta_4 * myX[, "gender"]


ITE <- mu_0 + tau * myZ

# Ajouter une colonne pi pour la probabilité théorique
data$pi <- 1 / (1 + exp(-(mu_0 + tau * myZ)))

list_q = quantile(100*data$pi, probs = c(0,0.1,0.25,0.5,0.75,0.9,1))
print(list_q)

ITE_proba <- 1 / (1 + exp(-(mu_0 + tau))) - 1 / (1 + exp(-mu_0))

list_q = quantile(100*ITE_proba, probs = c(0,0.1,0.25,0.5,0.75,0.9,1))
print(list_q)


bruit_gaussien <- rnorm(size_sample, mean = 0, sd = sqrt(hyperparams$sigma_sq))
myY <- plogis(ITE + bruit_gaussien)
list_q = quantile(100*myY, probs = c(0,0.1,0.25,0.5,0.75,0.9,1))
print(list_q)

```

```{r}
# Estimate the density
density_estimate <- density(100*data$pi, kernel = "gaussian")

data$pi %>% length()

# Plot the density
plot(density_estimate, main="Density Plot of Y", xlab="Y", ylab="Density")

# Optionally, add a rug plot to show the individual data points
rug(100*data$pi)
```

```{r}
# Estimate the density
density_estimate <- density(100*ITE_proba)

# Plot the density
plot(density_estimate, main="Density Plot of ITE", xlab="ITE", ylab="Density")

# Optionally, add a rug plot to show the individual data points
rug(ITE_proba)
```

```{r}
bruit_gaussien <- rnorm(size_sample, mean = 0, sd = sqrt(0.1))
myY <- plogis(ITE + bruit_gaussien)

# Estimate the density
density_estimate <- density(100*myY, kernel = "gaussian")

# Plot the density
plot(density_estimate, main="Density Plot of Y", xlab="Y", ylab="Density")

# Optionally, add a rug plot to show the individual data points
rug(100*myY)
```


```{r}
set.seed(123)
print(hyperparams$sigma_sq)

list_fac = list(0.1, 0.5, 1)

for (fac in list_fac){
  print(fac)
  # Observation de Y avec du bruit
  bruit_gaussien <- rnorm(size_sample, mean = 0, sd = sqrt(hyperparams$sigma_sq))
  myY <- plogis(ITE + bruit_gaussien * fac)
  
  diff_Y = 100 * (myY - data$pi)
  
  list_q = quantile(diff_Y, probs = c(0,0.1,0.25,0.5,0.75,0.9,1))
  print(list_q)
}
```

```{r}
set.seed(123)
print(hyperparams$sigma_sq)

list_fac = list(0.1, 0.5, 1,2 ,3, 5)

for (fac in list_fac){
  print(fac)
  # Observation de Y avec du bruit
  bruit_gaussien <- rnorm(size_sample, mean = 0, sd = sqrt(hyperparams$sigma_sq))
  myY <- plogis(ITE + bruit_gaussien * fac)
  
  diff_Y = 100 * (myY - data$pi)
  
  # Estimate the density
  density_estimate <- density(diff_Y, kernel = "gaussian")
  
  # Plot the density
  plot(density_estimate,main = paste("Density Plot of diff Y (fac =", fac, ")"), xlab="diff Y", ylab="Density")
  
  # Optionally, add a rug plot to show the individual data points
  rug(diff_Y)
}
```


```{r}
S_logit_int <- function(data){
  # Créer la formule avec les interactions spécifiques
  formula <- Y ~ age + weight + comorbidities + gender + treatment +
    treatment:age + treatment:weight + treatment:comorbidities + treatment:gender
  
  # Ajuster le modèle de régression logistique
  model <- glm(formula, data = data, family = binomial(link = "logit"))
  
  return(model)
}

res_S_int <- S_logit_int(data)
summary(res_S_int)
```

# Estimation de $pi$ à partir de données bruitées

```{r}
curr_dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(curr_dir); setwd('./../../')
data <- read.csv("./../Setup 1/Data/simulated_1M_data.csv")

MSE_100 <- function(x, y) sqrt(mean((100*x - 100*y)^2))

# Prédire les probabilités que Y soit égal à 1
logit_model <- res_S_int

# Calculer mu_0, tau, et ITE
mu_0 <- hyperparams$gamma_0 + hyperparams$gamma_1 * myX[, "age"] + hyperparams$gamma_2 * myX[, "weight"] + hyperparams$gamma_3 * myX[, "comorbidities"] + hyperparams$gamma_4 * myX[, "gender"]
tau <- hyperparams$delta_0 + hyperparams$delta_1 * myX[, "age"] + hyperparams$delta_2 * myX[, "weight"] + hyperparams$delta_3 * myX[, "comorbidities"] + hyperparams$delta_4 * myX[, "gender"]


ITE <- mu_0 + tau * myZ

# Ajouter une colonne pi pour la probabilité théorique
data$pi <- 1 / (1 + exp(-(mu_0 + tau * myZ)))

data$prob_logit_Y_1 <- predict(logit_model, type = "response")


MSE_100(data$pi,data$prob_logit_Y_1)
```

```{r}
# Création du plot de la MSE du la prédiction issu du logit
# en fonction de la taille de l'échantillon

# Création d'un vecteur de taille d'échantillon espacé en log
sample_size <- round(exp(seq(log(100), log(nrow(data)), length.out = 20)))


vec_MSE = c()
for (i in 1:length(sample_size)){
  size = sample_size[i]
  print(i)
  data_reduced = data[sample(nrow(data)),]
  data_reduced = data_reduced[1:size,]
  
  res_S_int <- S_logit_int(data_reduced) # correspond à fac = 1
  
  # Prédire les probabilités que Y soit égal à 1
  logit_model <- res_S_int
  data_reduced$prob_logit_Y_1 <- NA
  data_reduced$prob_logit_Y_1 <- predict(logit_model, type = "response")
  
  MSE_value = MSE_100(data_reduced$pi,data_reduced$prob_logit_Y_1)
  print(MSE_value)
  vec_MSE = c(vec_MSE, MSE_value)
}

plot(sample_size, vec_MSE, log="xy")
```


